blank_issues_enabled: false

contact_links:
  - name: Community Discussions
    url: https://github.com/vuella/vuella/discussions
    about: Please ask and answer questions here.

  - name: 📚 Vuella Documentation
    url: https://github.com/vuella/vuella#readme
    about: Check the documentation for usage of Vuella
